version: '3'
services:
  webapp:
    build: docker/app
    container_name: school_app
    ports:
      - 8080:8080
    volumes:
      - "${PWD}/docker/app/logs:/var/log/school"
    networks:
      - school_network
  db:
    build: docker/mysql
    container_name: school_db
    ports:
      - 3307:3306
    volumes:
      - "${PWD}/docker/mysql/data:/var/lib/mysql"
    networks:
      - school_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
networks:
  school_network: